### ISSUE TITLE
Update dependencies to use 'prop-types' package.

### ISSUE THREAD

**Issue by besrabasant** [talyssonoc/react-katex#11]
Can you update the repo to use `prop-types` package as using `React.PropTypes` gives warning.

I tried to update it but got stuck with uglify js plugin.

**Comment by talyssonoc** [comment]
I intend to release a major soon where I'll surely port it to use `prop-types`.

**Comment by besrabasant** [comment]
ETA ??

**Comment by talyssonoc** [comment]
I'm waiting for another PR to be merged and then gonna tackle this.

**Comment by besrabasant** [comment]
ok... By the way can you help me out why am i getting 
```
ERROR in react-katex.min.js from UglifyJs
Unexpected token: punc ({) [react-katex.min.js:57,8]
```
when running `npm run prepublish`

**Comment by besrabasant** [comment]
I have updated `webpack.config.js` to use `uglifyjs-webpack-plugin`

**Comment by talyssonoc** [comment]
Did you change anything in the code or just changed the plugin?

**Comment by besrabasant** [comment]
just changed the plugin

**Comment by talyssonoc** [comment]
What's at the line `react-katex.min.js:57,8`?

**Comment by besrabasant** [comment]
`export { default as InlineMath } from './InlineMath';`

**Comment by talyssonoc** [comment]
@besrabasant it seems to be working normally for me, check this PR: https://github.com/talyssonoc/react-katex/pull/12

**Comment by besrabasant** [comment]
still doesn't work for me..

**Comment by talyssonoc** [comment]
What problem are you having? You mean during the build of your app or just this lib?

**Comment by besrabasant** [comment]
![capture](https://user-images.githubusercontent.com/13284206/27495054-11221940-586e-11e7-820a-6dea067bf386.JPG)
I having this problem

**Comment by besrabasant** [comment]
just this lib

**Comment by talyssonoc** [comment]
Does it happen if you don't add `uglifyjs-webpack-plugin` dependency?

**Comment by besrabasant** [comment]
yes

**Comment by talyssonoc** [comment]
That's weird, are your changes equal to mine on my PR?

**Comment by besrabasant** [comment]
Yes... the changes are same

**Comment by talyssonoc** [comment]
Yep, looks like Babel is not transpiling it in your environment, it seems to be working for me though. For the path on your screenshot looks like you're trying to do that from inside your app's dependency folder? Can you try to do a `git clone` of the project in a different folder?

**Comment by besrabasant** [comment]
sure

**Comment by besrabasant** [comment]
Yeah that worked for me... :+1: ) maybe the issue was I was trying to do it inside the app's dependency folder.

**Comment by talyssonoc** [comment]
Good to know it worked! Anyway I got this in that PR, I'm gonna wait to merge it after the other PR that is in review to be merged and then update the other dependencies and release a major with this change.

**Comment by Hoten** [comment]
Hey @talyssonoc, is there anything I could do to help get this change in?
