### ISSUE TITLE
Use Rollup to bundling instead of Webpack

### ISSUE THREAD

**Issue by talyssonoc** [talyssonoc/react-katex#16]

**Comment by develerltd** [comment]
Is there a reason behind this request?

**Comment by talyssonoc** [comment]
@develerltd bundles with Rollup are smaller and [are better for libraries](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c). Even this lib being very small already, I think it's worth it to move to Rollup. I'm open to discuss that if you think it's not necessary!
