### ISSUE TITLE
Update proptypes

### ISSUE THREAD

**Issue by thomassuckow** [talyssonoc/react-katex#22]
In preparation for React 0.16, should update to using the prop-types package.
https://github.com/facebook/prop-types#prop-types

**Comment by talyssonoc** [comment]
It's already using it, I just didn't release the next version yet: https://github.com/talyssonoc/react-katex/blob/master/src/createMathComponent.js#L2

There are some last things before releasing v2, contributions are welcome! https://github.com/talyssonoc/react-katex/milestone/1
