### ISSUE TITLE
Not rendering using jsx?

### ISSUE THREAD

**Issue by jacobw56** [talyssonoc/react-katex#24]
Not sure if I'm just doing it wrong (new to react and jsx) but I seem to have everything setup correctly, but then I don't get the expected output.  Here is a pretty minimal App.js example where I grab a number from an api and try to display it:

    import React, { Component } from 'react';
    import logo from './logo.svg';
    import './App.css';
    import {BlockMath} from 'react-katex';
    
    class App extends Component {
      constructor(props) {
        super(props)
        this.state = {
          number: 0
        }
      }
      componentDidMount() {
        fetch('http://localhost:4001/api/get_number')
          .then(data => data.json())
          .then(data => {
            this.setState({
              number: data.number
            })
          })
      }
      render() {
        const number = this.state.number.toString()
        const number_block = React.createElement(BlockMath, null, number)
        //console.log(number_block)
        return (
          <div className="App">
            <p>
              Here is a number: {number_block}
            </p>
          </div>
        );
      }
    }
    
    export default App;

where `number = "-\frac{\pi}{54}"` and my output is:

    Here is a number:
    -\frac{\pi}{54}−54π​

Not sure why it writes the latex before rendering it, nor why the fraction doesn't render but the pi does?

**Comment by talyssonoc** [comment]
Hello @jacobw56, I'm gonna investigate the cause for that and try to fix it, thanks for the given example!

**Comment by talyssonoc** [comment]
@jacobw56 I can't seem to reproduce the problem, it's rendering correctly for me. Is there some way you can give me more context on this? Also, what is logged if you try to log `number`?

**Comment by jacobw56** [comment]
Hmmm, something must have been hinky somewhere... I just refreshed it this morning and everything works.  I'll see if I can recreate it again, and in the meantime I'll close the issue.  Sorry for the goosechase!

**Comment by talyssonoc** [comment]
There's no problem! Let me know when you recreate the bug.
