### ISSUE TITLE
Warning: <div> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by jacobw56** [talyssonoc/react-katex#25]
This is a quick one.  Since you use `div`s for your `dangerouslySetInnerHTML` elements, we get a warning that `<div> cannot appear as a descendant of <p>`.  You can fix this by changing them to `span` elements instead.  See [here](https://stackoverflow.com/questions/41928567/div-cannot-appear-as-a-descendant-of-p) and [here](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1).

**Comment by talyssonoc** [comment]
@jacobw56 I use `<div>` for the `BlockMath`, that is meant to be used as a separate block, outside of `<p>` elements. If you intend to use it inside paragraphs you should use `InlineMath`, what do you think?

**Comment by jacobw56** [comment]
I get the logic, I thought it would be common to use blocks inside paragraphs when doing proofs and such. For instance I imagined doing something like:

    <p>
        Let <InlineMath>f_n</InlineMath> be a sequence of <InlineMath>\mathbb{R}</InlineMath>-valued measurable functions on a measure space <InlineMath>(S, \sigma, \mu)</InlineMath>. Suppose that the sequence converges pointwise to a function <InlineMath>f</InlineMath> and is dominated by some integrable function <InlineMath>g</InlineMath> in the sense that <BlockMath>|f_n(x)| \leq g(x)</BlockMath> for all numbers <InlineMath>n</InlineMath> in the index set of the sequence and all points <InlineMath>x \in S</InlineMath>. Then <InlineMath>f</InlineMath> is integrable and <BlockMath>\lim_{n\to\infty}\int_S |f_n - f| d\mu = 0.</BlockMath>
    </p>

since this allows me to pretty much just search and replace the `$` and `$$` tags in my latex documents. If this isn't the typical pattern of usage then feel free to close the issue.  Thanks!

**Comment by talyssonoc** [comment]
Oh, I see! Yeah, the pattern for those cases is just to have a separate block since it's the HTML-way. Gonna close the issue then.
