### ISSUE TITLE
Possible issue rendering sqrt and frac?

### ISSUE THREAD

**Issue by jacobw56** [talyssonoc/react-katex#26]
Hey sorry to hit you with something else to look at, but I am getting results like the following.  I have an InlineMath that should be rendering `-\frac{\pi}{5} - 7912 \times i` but I am getting this output:

<img width="536" alt="screen shot 2017-09-02 at 10 35 49 am" src="https://user-images.githubusercontent.com/8697597/29996339-fb041926-8fca-11e7-8f0c-bfb777983654.png">

I seem to be consistently getting this with fractions and square roots, but the tex input looks correct to me.  Not sure if this is your issue or if it trickles down from katex or what.  Packages are `katex@0.8.3` and `react-katex@1.2.0`.  Let me know what info I can provide to help.

**Comment by talyssonoc** [comment]
Hey, @jacobw56, sorry for the delay on that. I'm gonna investigate and get back to you with what I found out!

**Comment by jacobw56** [comment]
I figured this one out.  I was using the 0.8.3 version of katex.min.css, when I revert to the 0.7.1 version it works.  If I get a chance I might try to look into why that happens.

**Comment by talyssonoc** [comment]
Oh, it makes sense! Maybe the 0.8.3 version of KaTeX changed some CSS class or markup that doesn't exist in the version declared on peerDependencies https://github.com/talyssonoc/react-katex/blob/v1.2.0/package.json#L33. Thanks!
