### ISSUE TITLE
Published package v1.2.0 on NPM is behind master

### ISSUE THREAD

**Issue by mattread90** [talyssonoc/react-katex#27]
Would it be possible to publish the latest version to NPM? I see that the latest source on master uses the external prop-types package as opposed to the old built-in React PropTypes.

As React 16 has been released and doesn't include the prop-types package anymore, react-katex is not compatible with it. Including the latest dist from master in my React 16 project seems to work fine, so it would be great to have a release for this :)

Thanks for the great package!

**Comment by mattread90** [comment]
Apologies, I hadn't spotted the v2.0 milestone that's in progress. Still, I feel like the plus of supporting React 16 is worth a new release without the other remaining issues being resolved. I will try to take a look at the other issues though

**Comment by dudko** [comment]
New [version](73faa887aeaa31598691d238a20095e63829f6ec) released.
