### ISSUE TITLE
Support for New Versions of React

### ISSUE THREAD

**Issue by perkss** [talyssonoc/react-katex#28]
In package.json I do have
"katex": "^0.9.0-beta","react": "^16.2.0", "react-katex": "^1.2.0",

When importing: `import { BlockMath } from 'react-katex';`

I  get the error Uncaught TypeError: Cannot read property 'string' of undefined at Object.<anonymous> (bundle.js:65414) at __webpack_require__ (bundle.js:65334) at Object.<anonymous> (bundle.js:65367) at __webpack_require__ (bundle.js:65334) at bundle.js:65354 at bundle.js:65357 at webpackUniversalModuleDefinition (bundle.js:65307) at Object.<anonymous> (bundle.js:65314) at __webpack_require__ (bundle.js:20) at Object.defineProperty.value

Along with warnings when building:

npm install --save react-katex npm WARN react-katex@1.2.0 requires a peer of katex@^0.7.0 but none is installed. You must install peer dependencies yourself. npm WARN react-katex@1.2.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself. npm WARN react-latex@1.0.1 requires a peer of react@^15.3.0 but none is installed. You must install peer dependencies yourself.

So it seems a bit odd this maybe is the newer version of React supported?

I did try this which maybe related by installing prop types but didnt seem to make a difference installing that.

Setting the versions to this solves the problem:
Removing the warnings has worked so setting the values to:
"react-katex": "1.2.0",
"katex": "^0.7.0",
"react": "15.3.2",

**Comment by episodeyang** [comment]
@talyssonoc I am running into the same problem. Seems that this will require an update on the dist.

**Comment by dudko** [comment]
As @talyssonoc commented, it's an issue with outdated module distribution. Release `1.2.0` points to old commit that still uses PropTypes from react.

Until new release, you can install the module directly from github with
```
npm i https://github.com/talyssonoc/react-katex.git
```
and then use it with the following import statement

```js
import { InlineMath } from "react-katex/dist/react-katex";
```

**Comment by sjorsvanheuveln** [comment]
You mean this error?? :
```
You may need an appropriate loader to handle this file type.
| 
| const InlineMath = ({ html }) => {
|   return <span dangerouslySetInnerHTML={{__html: html}} />;
| };
```

**Comment by dudko** [comment]
@sjorsvanheuveln, yes. That's the error you gonna see after starting react app.

**Comment by dudko** [comment]
New [version](73faa887aeaa31598691d238a20095e63829f6ec) released.
