### ISSUE TITLE
Double text display from component

### ISSUE THREAD

**Issue by sjorsvanheuveln** [talyssonoc/react-katex#31]
Using both components, my math expressions are being outputted twice. Any idea what's the deal?

**Comment by dudko** [comment]
@sjorsvanheuveln , could you please post sample of your code?

**Comment by conradkdotcom** [comment]
I had the same issue, @sjorsvanheuveln . It's because I didn't include the Katex CSS file as recommended in Katex's "Usage" section. https://github.com/Khan/KaTeX#usage

**Comment by dudko** [comment]
@sjorsvanheuveln and @conradkdotcom thansk for your feedback. I can confirm that KaTeX outputs expressions twice, if the required css is not provided.

It would be hard to determine whether required css is available from `react-katex` component, check this [thread](https://stackoverflow.com/questions/983586/how-can-you-determine-if-a-css-class-exists-with-javascript), and even might not be feasible.
