### ISSUE TITLE
Issue on run

### ISSUE THREAD

**Issue by sjorsvanheuveln** [talyssonoc/react-katex#32]
Hi there, 

I would like to use your package, but I can't seem to get it working. I'm getting the following error:

`TypeError: undefined is not an object (evaluating '_react2.default.PropTypes.string')`

**Comment by lillydinhle** [comment]
Hi! I had the same issue using react 16. @dudko's suggestion [here](https://github.com/talyssonoc/react-katex/issues/28) worked for me.
Here's to hoping it works for you too!

**Comment by dudko** [comment]
New [version](73faa887aeaa31598691d238a20095e63829f6ec) resolves this issue.
