### ISSUE TITLE
Upgrade to Katex 0.7

### ISSUE THREAD

**Issue by lifeiscontent** [talyssonoc/react-katex#4]
Any plans to upgrade?

**Comment by talyssonoc** [comment]
Oops, I didn't notice 0.7 was already released, gonna upgrade 😄

**Comment by lifeiscontent** [comment]
@talyssonoc great news! Thanks 👍

**Comment by talyssonoc** [comment]
Done!

**Comment by lifeiscontent** [comment]
@talyssonoc 0.7.1 is out actually. 😅

**Comment by talyssonoc** [comment]
0.7.1 satisfies the ^0.7.0 version constraint :)

Em 13 de fev de 2017 8:54 AM, "Aaron Reisman" <notifications@github.com>
escreveu:
