### ISSUE TITLE
请问，我使用react-katex组件的时候，发现如果字符串中包含中文的时候，就会报错

### ISSUE THREAD

**Issue by zuwensong** [talyssonoc/react-katex#43]
请问，我使用react-katex组件的时候，发现如果字符串中包含中文的时候，就会报错

例：
![image](https://user-images.githubusercontent.com/18671875/40960774-51dd3c5a-68d3-11e8-8295-9a6fe01644ad.png)

错误信息：
![image](https://user-images.githubusercontent.com/18671875/40960732-36e79c9c-68d3-11e8-88f2-5093346bf911.png)

请问如何支持中文字符呢

**Comment by dudko** [comment]
@zuwensong , according to https://github.com/Khan/KaTeX/issues/380, katex should support [CJK](https://en.wikipedia.org/wiki/CJK_characters) characters.

Apparently there are still some issues. `react-katex` is just passing the string down to katex library. It's not responsible for parsing.

Have you tried to wrap your text into `\text{}`?
```js
<BlockMath math={'\\text{你好}'} />
```

**Comment by chuxusave** [comment]
你好，请问解决了吗？我也想实现类似的功能

**Comment by dudko** [comment]
@chuxusave , I don't think so. I've mentioned workaround in my previous comment. Have you tried it?

**Comment by lesca** [comment]
> @zuwensong , according to [KaTeX/KaTeX#380](https://github.com/KaTeX/KaTeX/issues/380), katex should support [CJK](https://en.wikipedia.org/wiki/CJK_characters) characters.
> 
> Apparently there are still some issues. `react-katex` is just passing the string down to katex library. It's not responsible for parsing.
> 
> Have you tried to wrap your text into `\text{}`?
> 
> ```js
> <BlockMath math={'\\text{你好}'} />
> ```

Wonderful! This is the answer! Works like a charm!
