### ISSUE TITLE
How to escape brackets?

### ISSUE THREAD

**Issue by awatson1978** [talyssonoc/react-katex#6]
Hi there,
Any idea on how to escape brackets?  I'm trying to create some more complex equations that involve fractions and use the katex bracket notation, but React is trying to handle the brackets instead.

http://tiddlywiki.com/plugins/tiddlywiki/katex/

I've tried escaping the characters a couple different ways, but nothing has worked yet.  

Example:
```js
// this fails
<BlockMath>Foo = \frac{x}{y}</BlockMath>

// was hoping for 
// Foo = x/y

// this also fails
<BlockMath>Foo = \frac\{x\}\{y\}</BlockMath>

// fail
<BlockMath>Foo = \frac/{x/}/{y/}</BlockMath>

// fail :(
<BlockMath>Foo = \frac &#123 x &#125 &#123 y &#125</BlockMath>

```

Otherwise, thanks for the great library!  Very useful!  Just want to use it for more complex equations.  :)
Abigail

**Comment by talyssonoc** [comment]
Hey there, thanks for the feedback!

For more complex cases with brackets you can use the alternative way to pass data to the tag:

```javascript
<BlockMath math="Foo = \\frac{x}{y}" />
```

**Comment by awatson1978** [comment]
Ah!  Very good.  Had an extra slash in there, but got it working.  Solution was the following:
```js
<BlockMath math="Foo = \frac{x}{y}" />        
```
Thank you for the help!

**Comment by Venryx** [comment]
You should also be able to do this, by the way:
```
<BlockMath>{"Foo = \\frac{x}{y}"}</BlockMath>
```

Or this: (nice if you want multiline)
```
<BlockMath>{`
Foo = \\frac{x}{y}
    ... other stuff
`}</BlockMath>
```
