### ISSUE TITLE
Possibly contact KaTeX creators?

### ISSUE THREAD

**Issue by Venryx** [talyssonoc/react-katex#7]
Have you contacted the creators of KaTeX about possibly having this project be recognized/adopted as an extension of KaTeX?

I know they're familiar with React things, eg: https://github.com/Khan?q=react

Just wondering, as that could help it have better maintenance, if it's an official module. (of course, there's also some disadvantages, such as possibly less control)

**EDIT**

Another option is to just mention it to them, so they can include a link to this project on their readme page. (like they do [here](https://github.com/Khan/KaTeX#automatic-rendering-of-math-on-a-page), for the auto-render extension)

In my case, I found this extension by searching on google, but many people won't do that. Having it mentioned at least will help improve discoverability.

**PS** Also, (in case you're not yet aware of it), there's a similar "react-latex" module here (https://github.com/zzish/react-latex), which seems aimed at doing about the same thing as this module does. (it uses katex as well)

Not sure which is better, though will use this for now, since it has more stars. 😄

**Comment by talyssonoc** [comment]
I didn't contact them yet, but it seems a good idea, gonna do it, thanks!

About the another react-latex, I'm aware of it but I don't like the way it works, it parses stuff internally and I think it makes it more complex.

**Comment by dudko** [comment]
I did so in this [PR](https://github.com/Khan/KaTeX/pull/1236).
