### ISSUE TITLE
Letters looking thin and strange

### ISSUE THREAD

**Issue by JakovGlavac** [talyssonoc/react-katex#73]
Hi,
I'm using a react-katex library with remix.run and for some reason, formulas look strange.
![image](https://user-images.githubusercontent.com/34971091/154163395-14ad1938-2ad7-4f13-9561-6d667ae46d8a.png)

Here is the tex:
```tex
\mathrm{R}_{u}=\frac{\Delta U}{\Delta I} \Rightarrow \mathrm{R}_{u}=\frac{U_{2}-U_{1}}{I_{1}-I_{2}} \Rightarrow \mathrm{R}_{u}=\frac{U_{2}-U_{1}}{\frac{U_{1}}{R_{1}}-\frac{1}{3} \cdot \frac{U_{1}}{R_{1}}} \Rightarrow \mathrm{R}_{u}=\frac{U_{2}-U_{1}}{\frac{2}{3} \cdot \frac{U_{1}}{R_{1}}}=\frac{10-5}{\frac{2}{3} \cdot \frac{5}{R_{1}}}=\frac{5}{\frac{10}{3 \cdot R_{1}}}=\frac{15 \cdot R_{1}}{10}=1.5 \cdot R_{1}
```

I don't really know what is wrong or where to start with fixing it.

**Comment by talyssonoc** [comment]
Styling is not directly handled by react-katex, it is delegated to Katex and its CSS file. For this case, it could be either the CSS file is not being correctly imported or there is some other CSS affecting the rendering.
