### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Venryx** [talyssonoc/react-katex#8]
It would be nice if there were a way to handle "KaTeX parse errors", without the component failing in the constructor (generateHtml) function.

Perhaps an "onError" property: if it's specified, errors in katex.renderToString(latex) will be caught, and sent to the onError function for custom handling -- perhaps having the return value of it being what will be displayed in place of the formula. (in my case, I'd just render the parsing error as plain-text, in place of the formula)

In my project, the reason this is needed is because the website content is created by the users, so they can enter formulas themselves. And I don't want them to get confused by the project-level error message boxes that currently show up (from uncaught errors) -- instead, a localized message would be more helpful.

**Comment by talyssonoc** [comment]
That's a very nice idea! Would you be interested in sending a PR for that?
